server:
  port: ${SERVER_PORT:8081}
  error:
    whitelabel:
      enabled: true
  servlet:
    encoding:
      force: true
spring:
  application:
    name: Qring
  # 读取多语言资源信息
  messages:
    basename: classpath:i18n/messages;classpath:i18n/common;classpath:i18n/validate
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.54.182.186:3306/crashcourse?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&useSSL=false
    username: root
    password: oo000000
    #连接池
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 120000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  quartz:
    #持久化到数据库方式
    job-store-type: jdbc
  # knife4j设置
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    activate:
      on-profile:
        - dev

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 分页工具设置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    root: INFO
    com.baomidou.mybatisplus: DEBUG
    mapper: DEBUG
